### ISSUE TITLE
error on remote-ssh

### ISSUE THREAD

**Issue by ihakh** [danielroedl/vsc-meld-diff#10]
when I connect with` ssh -X` to remote develop server I can run meld
but with remote-ssh extension
and this extension I get this error:
```
Meld Diff Error: Error running diff command! StdErr: Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(meld:45279): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/meld", line 244, in <module>
    setup_resources()
  File "/usr/bin/meld", line 183, in setup_resources
    Gtk.IconTheme.get_default().append_search_path(icon_dir)
AttributeError: 'NoneType' object has no attribute 'append_search_path'
```

**Comment by HITChris** [comment]
I'm also having trouble with this. Any ideas?

**Comment by danielroedl** [comment]
When you define the x11 forwarding in your connection it works.
By adding a new connection use `ssh -X user@host`.
Check in your ~/ssh/config if `ForwardX11 yes` is configured for your added connection.

You can also allow X11 forwarding in general by adding to your ~/.ssh/config:
```
Host *
  ForwardAgent yes
  ForwardX11 yes
```
I hope this helps.

**Comment by Xudong-Huang** [comment]
maybe we can get some idea from https://github.com/mbikovitsky/beyond-ssh.git

**Comment by DeadRabbits307** [comment]
still no progress? Is there a configuration for remote-ssh extension needed? I set `ForwardAgent  `and `ForwardX11`, no success. 
Starting `meld` in VScodes terminal (Terminal -> New terminal) works fine. What is the difference between starting meld in the terminal and by right click "Compare all selected files using meld"?

**Comment by DeadRabbits307** [comment]
for me (I also work remotely) worked following:

[Remote X11](https://marketplace.visualstudio.com/items?itemName=spadin.remote-x11), [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) and [Remote X11 (SSH)](https://marketplace.visualstudio.com/items?itemName=spadin.remote-x11-ssh) running

in file `~/.ssh/config` I had to add following entry:
```
Host * 
  SetEnv DISPLAY=localhost:10.0
```
(the actual number (here 10.0) you can verify by an `echo $DISPLAY`)

in file `/etc/ssh/sshd_config` on the remote Linux Workstation 
```AcceptEnv DISPLAY```
